# Generated by Django 4.2.7 on 2023-11-24 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(blank=True, max_length=100, null=True)),
                ('whatsapp', models.IntegerField(max_length=10)),
                ('email', models.EmailField(max_length=200)),
                ('pais_destino', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_viaje', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
