# Generated by Django 4.2.7 on 2023-11-24 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cita_licencia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha_viaje',
            field=models.DateField(null=True),
        ),
    ]
