# Generated by Django 4.2.7 on 2023-11-24 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cita_licencia', '0002_alter_cliente_fecha_viaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha_viaje',
            field=models.DateField(blank=True, null=True),
        ),
    ]
